@startuml
:用户打开活动列表页，选择要参加的活动，每个活动绑定一个商品，
这个活动页面下面会展示最早开团还没成团的团购;
:用户点击该商品下单，跳转到下单页;
:用户需要选择地址，支付方式;
if(支付) then(点击取消)
:进行订单支付页;
end;
else(支付成功)
:开启一起团购订单，跳转到团购页面，可以分享;
end;

:非首单用户参与拼团;
:打团参团信息页，点击拼单;
:跳转下单页，选择地址，支付方式;
:支付;
:校验订单是否完成;




@enduml